name: docs_mvp-ale
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton




    # Pip-only installs
  - pip:
    - -e ../

